### PR TITLE
Support equal signs inside attribute values

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Allows for attributes to have values that include quotes, for example urls that include search parameters.

### CODE REVIEW

**Comment by djm** [comment]
@ChristianMurphy I forgot I automated it with Travis. v0.1.5 is on its way out.

Thanks again :)

**Comment by ChristianMurphy** [comment]
It looks like the npm release got stuck at
```
You cannot publish over the previously published versions: 0.1.4. : remark-shortcodes
```
https://travis-ci.org/djm/remark-shortcodes/jobs/370783888#L553

**Comment by djm** [comment]
Oops, forgot to bump the package version. Succeeded this time :)

**Comment by ChristianMurphy** [comment]
Thanks @djm! :bow:

**Pull request merged**
